version: '3'

services:
  web:
    build: .
    ports:
      - "8082:80"  # Map port 8080 on the host to port 80 in the container
    volumes:
      - .:/usr/share/nginx/html  # Sync project files with the container